# -*- coding: utf-8 -*-
"""Soczyste rabaty.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfU5lwdNa2GOPWmQ9-URaf30VnlBzQC0
"""

#importowanie potrzebnych bibliotek
import os
import openpyxl
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt
import plotly.express as px
import plotly.graph_objects as go
from urllib.request import urlopen
import json
import io
import datetime



st.set_page_config(page_title='Łączenie danych do kalendarza', layout='wide')



tabs_font_css = """
<style>
div[class*="stTextInput"] label {
  font-size: 26px;
  color: black;
}
div[class*="stSelectbox"] label {
  font-size: 26px;
  color: black;
}
</style>
"""

st.title("Automat KDW")



################### RAPORT PROMOCYJNY ####################
df_p = st.file_uploader(
    label = "Wrzuć plik RaportPromocyjny"
)
if df_p:
    df_p = pd.read_csv(df_p, sep=';')
    st.write(df_p.head())

# Wybieranie tylko określonych kolumn z DataFrame
kolumny_p = [
    'Id Materiału', 'identyfikator promocji', 'Nazwa Promocji', 'Nr zlecenia', 'Skład (SPR,SGL)', 'Rabat Promocyjny'
]
df_p = df_p[kolumny_p]


###################### ASORTYMENT NEUCA ########################
df_a = st.file_uploader(
    label = "Wrzuć plik Asortyment Neuca"
)
if df_a:
    df_a = pd.read_excel(df_a, sheet_name='Asortyment')
    st.write(df_a.head())

# Wybieranie tylko określonych kolumn z DataFrame
kolumny_a = [
    'Indeks kartoteki', 'Cena Neuca', 'EAN', 'BLOZ'
]

df_a = df_a[kolumny_a]


####################### WSADOWY #########################
df_file = st.file_uploader(
    label="Wrzuć plik wsadowy"
)

if df_file:
    # Wczytanie dwóch arkuszy jako osobne DataFrame'y
    df_oltarzew = pd.read_excel(df_file, sheet_name='Ołtarzew')
    df_total = pd.read_excel(df_file, sheet_name='Total')
    
    # Wyświetlenie pierwszych kilku wierszy dla obu arkuszy
    st.write("Arkusz Ołtarzew:")
    st.write(df_oltarzew.head())
    
    st.write("Arkusz Total:")
    st.write(df_total.head())




